### ISSUE TITLE
Format support

### ISSUE THREAD

**Issue by roychen1998** [fanyingming/YUVPlayer#2]
HI Yingming,

Thanks very much for sharing the project, actually this is the best YUV viewer I have known.
But it is a pity that YUV422/YUV444/RGB and 10bit/12bit input data is not yet supported in your depote. Do you have got any plan on supporting more formats in this YUVplayer? 
BTW, I think to add English support and a license term might be helpful.

Best Regard,
Roy

**Comment by fanyingming** [comment]
Hi Roy,

I have no plane to support more function.

This project under MIT license.

Thanks.
